/*
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will 
be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>

int fib(int n){//n=2 {1}, n=3 {2}, n=4 {3}, n=5 {5}
    if (n <= 2){
        return 1;
    }else{
        return fib(n-1) + fib(n-2);
    }
}

int main(){
    int doesNotExceed = 4000000; 
    int sum = 0; int i = 2; int count=1;
    while(fib(i) < doesNotExceed){
        if(fib(i)%2==0){
            printf("Term %d: %d\n", count, fib(i));
            sum += fib(i); count++;
        }
        i++;
    }
    printf("\nSum of even terms that do not exceed %d: %d\n", doesNotExceed, sum);
    return 0;
}